title: Dino Liu
subtitle: My blog
link: Homepage link
meta:
  description: Content of description meta tag
  keywords: !!seq
    - C#, ASP.NET, ASP.NET MVC, Javascript, SQL Server, HTML, CSS.
    - English
  author: Dino Liu (Shawdren) <jl_lsj@163>
master:
  name: Dino Liu
  about: Try to do everything
  email: jl_lsj@163.com
rss:
  title: RSS feed title
  desc: RSS feed description
  lang: zh-cn
  max: 10
copyright:
  owner: Copyrighter
  beginYear: 2014
  endYear: 2014
theme: default
codetheme: night
